only-init: true

mongo:
  uri: ""
  username: ""
  password: ""

mysql:
  uri: ""
  username: ""
  password: ""
  database: ""

cf-r2:
  judge-data:
    url: ""
    token: ""
    key: ""
    secret: ""

go-judge:
  url: ""
