auth:
  jwt: ""
  connect: ""

feishu:
  notify-robot: ""
  app:
    test:
        app-id: ""
        app-secret: ""
        encrypt-key: ""
        verification-token: ""
        open-ids:
            test: ""
  chat:
    group:
      test: ""
