auth:
  jwt: ""
  connect: ""

roles:
  r-admin:
    - i-manage-web
    - i-manage-problem
    - i-manage-problem-daily
    - i-manage-judge
    - i-manage-contest
    - i-manage-collection
    - i-manage-discuss

feishu:
  notify-robot: ""
  app:
    test:
        app-id: ""
        app-secret: ""
        encrypt-key: ""
        verification-token: ""
        open-ids:
            test: ""
  chat:
    group:
      test: ""

remote:
  hdu:
    username: ""
    password:
